[context.production.environment]
  API_URL = "http://monitorapi.acmascis.com"

[context.staging.environment]
  API_URL = "http://monitorapistaging.acmascis.com"

[context.development.environment]
  REACT_APP_API_URL = "https://monitorapistaging.acmascis.com"
