[context.production]
  API_URL = "http://monitorapi.acmascis.com"

[context.staging]
  API_URL = "http://monitorapistaging.acmascis.com"

[context.development]
  API_URL = "http://monitorapistaging.acmascis.com"
